title: Chentao Zhang's Homepage
page-top-title: Chentao Zhang
top-section-bg-text: Artificial Intelligence & Software Engineering
home-subtitle: Chentao Zhang &ensp;|&ensp;张辰涛
copyright-text: '&copy; Chentao Zhang 2025-2027. All Rights Reserved.'
